"""Initial migration.

Revision ID: 6d7b7e33ca26
Revises: 
Create Date: 2024-10-25 12:00:34.270105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7b7e33ca26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), server_default='Default Name', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('child_name', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=150), nullable=False),
    sa.Column('fee_balance', sa.Float(), nullable=False),
    sa.Column('finance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finance_id'], ['finance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=150), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_marks')
    op.drop_table('student_fees')
    op.drop_table('teachers')
    op.drop_table('parents')
    op.drop_table('finance')
    op.drop_table('users')
    # ### end Alembic commands ###
